# Generated by Django 5.2.9 on 2026-01-04 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(blank=True, null=True, upload_to='ads/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClickEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(max_length=50)),
                ('browser', models.CharField(max_length=200)),
                ('operating_system', models.CharField(max_length=100)),
                ('referrer_url', models.TextField()),
                ('page_url', models.TextField()),
                ('click_duration', models.FloatField()),
                ('mouse_movement', models.FloatField()),
                ('scroll_depth', models.FloatField()),
                ('keystrokes_detected', models.IntegerField()),
                ('ad_position', models.IntegerField()),
                ('time_since_last_click', models.FloatField()),
                ('click_frequency', models.IntegerField()),
                ('VPN_usage', models.BooleanField(default=False)),
                ('fraud_probability', models.FloatField(blank=True, null=True)),
                ('fraud_label', models.CharField(blank=True, choices=[('fraud', 'Fraud'), ('legit', 'Legit')], max_length=10, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accuracy', models.FloatField()),
                ('precision', models.FloatField()),
                ('recall', models.FloatField()),
                ('f1_score', models.FloatField()),
                ('roc_auc', models.FloatField()),
                ('trained_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
